---
title: "Inscrição"
output:
  html_document:
    toc: false
---

```{r, include=FALSE}
source("setup_knitr.R")
```

<div class="panel panel-warning">
  <div class="panel-heading">**Atenção**</div>
  <div class="panel-body">
  - As inscrições são **gratuitas**, portanto solicitamos que se inscrevam
    somente aqueles que **realmente** participarão do evento.
  - O prazo máximo para inscrição é **22/04/2018**.
  - Para se inscrever e participar do R Day, é necessário **ler e
  concordar** com os termos do **código de conduta** abaixo.
  </div>
</div>

## Código de conduta

Todas as conferências endossadas pela [The R
Foundation](https://www.r-project.org/foundation) devem ter um código de
conduta para garantir um ambiente livre de assédios para todos os
participantes. Veja mais a respeito nesta
[página](https://www.r-project.org/behaviour.html).

## Código de conduta do R Day

Todos os participantes, palestrantes, apoiadores e voluntários do R Day
são obrigados a concordar com o seguinte código de conduta. Os
organizadores deverão garantir os termos deste código ao longo do
evento. Esperamos a cooperação dos participantes para ajudar a garantir
um ambiente seguro para todos.

### Versão rápida

Os organizadores do R Day são dedicados a fornecer uma experiência de
conferência sem assédio para todos, independentemente do sexo,
identidade e expressão de gênero, idade, orientação sexual, deficiência,
aparência física, tamanho corporal, raça, etnia ou religião (ou falta
dela). Nós não toleramos o assédio aos participantes do R Day de
qualquer forma. Linguagem sexual e imagens não são apropriadas para
qualquer local do evento, incluindo conferências, tutoriais,
apresentações, Twitter e outras mídias online. Os participantes do R Day
que violarem essas regras podem ser sancionados ou expulsos da
conferência.

### Versão longa

O assédio inclui comentários verbais ofensivos relacionados ao gênero,
identidade e expressão de gênero, idade, orientação sexual, deficiência,
aparência física, tamanho corporal, raça, etnia, religião, imagens
sexuais em espaços públicos, intimidação deliberada, perseguição,
seguimento, assédio de fotografia ou gravação, interrupção sustentada de
conversações ou outros eventos, contato físico inapropriado e atenção
sexual indesejável.

Os participantes solicitados à interromper qualquer comportamento de
assédio, deverão cumprir imediatamente.

Os apoiadores também estão sujeitos à política anti-assédio. Em
particular, os apoiadores não devem usar imagens, atividades ou
outros materiais sexualizados.

Se um participante apresentar comportamento de assédio, os organizadores
do R Day podem tomar as medidas que considerem adequadas, incluindo
alertar o infrator ou a expulsão do evento.

Se você está sendo assediado, observou que alguém está sendo assediado
ou tem outras preocupações, entre em contato com um membro da comissão
organizadora do R Day imediatamente.

Os organizadores do R Day estarão dispostos em ajudar os participantes a
entrar em contato com a segurança do Campus ou com a aplicação da lei
local, fornecer escoltadores ou, de outra forma, ajudar aqueles que
sofrem de assédio para se sentirem seguros durante a vigência do evento.

Esperamos que os participantes sigam essas regras em todas as etapas do
evento (incluindo todas as atividades e *coffee break*).

<div class="panel panel-primary">
  <div class="panel-heading">**Formulário de inscrição**</div>
  <div class="panel-body">
  A inscrição no R Day deve ser feita através deste
  [formulário](https://coletum.com/pt_BR/account/2742/form/4045/answer/new).
  </div>
</div>
