---
title: "Propostas"
output:
  html_document:
    toc: false
---

```{r, include=FALSE}
source("setup_knitr.R")
```

Todos os interessados são convidados a enviar propostas para
apresentações orais (projetos e pacotes em R) e tutorias (diversas
ferramentas).

<div class="panel panel-warning">
  <div class="panel-heading">**Prazos para envio de propostas**</div>
  <div class="panel-body">As propostas para apresentações orais e
  tutoriais devem ser enviadas entre **20/12/2017** e
  **08/04/2018**.</div>
</div>

## Apresentações orais

As apresentações orais terão duração total de 20 minutos (15 minutos de
exposição e 5 minutos para discussão). Serão consideradas propostas para
apresentação de pacotes desenvolvidos em R ou projetos que usam o R como
principal ferramenta. Ao total serão 9 apresentações.

As propostas para apresentação oral devem conter as seguintes
informações:

- Nome do apresentador
- Email
- Universidade/Instituição/Empresa
- Título
- Resumo
- Público-alvo (geral/específico)

<div class="panel panel-primary">
  <div class="panel-heading">**Formulário para envio de proposta de
  apresentação oral**</div>
  <div class="panel-body">
  ~~As informações devem ser preenchidas e encaminhadas através deste
  formulário.~~

  Período encerrado!
</div>
</div>

## Tutoriais

Ao total serão 8 tutorias, com duração de 1 hora cada. Foram pensados em
4 tutorias destinados a usuários em geral (ímpares), e 4 tutoriais
destinados a desenvolvedores (pares).

Os temas inicialmente propostos são os seguintes:

**Tutoriais para usuários:**

- **T1: Visualização de dados**
  - Ferramentas para visualização de dados, pacotes como `lattice`,
    `ggplot2`, técnicas de visualização, etc
- **T3: Manipulação de dados**
  - Ferramentas para importação, organização, resumo, formatação e
  exportação de dados, etc
- **T5: Editores para R**
  - Uso de editores como RStudio, Emacs, Tinn-R, Vim, para
    desenvolvimento em R
- **T7: Ferramentas para pesquisa reproduzível**
  - Ferramentas para pesquisa reproduzível, documentos dinâmicos, etc

**Tutoriais para desenvolvedores:**

- **T2: Paralelização de código**
  - Ferramentas para paralelização de códigos em R, uso de clusters, etc
- **T4: Desenvolvimento de pacotes**
  - Ferramentas para criação e manutenção de pacotes em R, `devtools`,
  `roxygen2`, etc
- **T6: R com linguagens externas**
  - Ferramentas para utilizar códigos de outras linguagens no R, como
  C, C++, Fortran, etc
- **T8: Desenvolvimento em Shiny**
  - Ferramentas e técnicas para desenvolvimento de aplicações em Shiny

<div class="panel panel-warning">
  <div class="panel-heading">**Importante**</div>
  <div class="panel-body">Os temas para tutorias expostos aqui foram
  propostos inicialmente pela comissão organizadora, mas **também serão
  aceitas propostas para outros temas**.</div>
</div>


As propostas para tutoriais devem conter as seguintes informações:

- Nome
- Email
- Universidade/Instituição/Empresa
- Título
- Destinado à: usuário/desenvolvedor/não se aplica
- Objetivo
- Nível (iniciante/intermediário/avançado)
- Pré-requisitos (se houver)
- Descrição

<div class="panel panel-primary">
  <div class="panel-heading">**Formulário para envio de proposta de
  tutorial**</div>
  <div class="panel-body">
  ~~As informações devem ser preenchidas e encaminhadas através deste
  formulário~~.

  Período encerrado!
  </div>
</div>

## Custeio

Até o momento o evento está sendo organizado de forma voluntária,
portanto não conta ainda com financiamento ou patrocinadores. Sendo
assim, por ora não existe garantia alguma de apoio financeiro aos
convidados e participantes do evento. Gentilmente, solicita-se que o
envio das propostas, portanto, não seja dependente de contrapartidas
financeiras por parte da organização do evento, ficando inicialmente, as
despesas de responsabilidade dos proponentes. Havendo êxito no
recebimento de qualquer auxílio, poderá haver ressarcimento parcial, ou
até total, das despesas dos convidados.
