+++
title = "Propostas"
id = "propostas"
formspree = true
+++

Todos os interessados são convidados a enviar propostas para
apresentações orais (projetos e pacotes em R) e tutorias (diversas
ferramentas).

### Apresentações orais

As apresentações orais terão duração total de 20 minutos (15 minutos de
exposição e 5 minutos para discussão). Serão consideradas propostas para
apresentação de pacotes desenvolvidos em R ou projetos que usam o R como
principal ferramenta. Ao total serão 9 apresentações.

As propostas para apresentação oral devem conter as seguintes
informações:

- Nome do apresentador
- Email
- Universidade/Instituição/Empresa
- Título
- Resumo
- Público-alvo (geral/específico)

Estas informações devem ser preenchidas e encaminhadas através deste
[formulário](https://goo.gl/forms/7jdfJZvPmdfg5psc2).

### Tutoriais

Ao total serão 8 tutorias, com duração de 1 hora cada. Foram pensados em
4 tutorias destinados a usuários em geral (ímpares), e 4 tutoriais
destinados a desenvolvedores (pares).

Os temas inicialmente propostos são os seguintes:

**Tutoriais para usuários:**

- **T1: Visualização de dados**
  - Pacotes como `lattice`, `ggplot2`, técnicas de visualização, etc)
- **T3: Manipulação de dados**
  - Pacotes e técnicas para manipulação, formatação, "limpeza" de dados,
  etc)
- **T5: Editores para R**
  - Uso do R em diferentes editores como RStudio, Emacs, Vim, etc)
- **T7: Ferramentas para pesquisa reproduzível**
  - Pacotes para pesquisa reproduzível, documentos dinâmicos, etc)

**Tutoriais para desenvolvedores:**

- **T2: Paralelização de código**
  - Pacotes e demais ferramentas para paralelização de códigos em R,
  etc)
- **T4: Desenvolvimento de pacotes**
  - Formas de criação e manutenção de pacotes em R, `devtools`,
  `roxygen2`, etc)
- **T6: R com linguagens externas**
  - Pacotes e formas de utilizar códigos de outras linguagens no R, como
  C, C++, Fortran, etc)
- **T8: Desenvolvimento em Shiny**
  - Ferramentas e técnicas para desenvolvimento de aplicações em Shiny)

**Importante:** Os temas para tutorias expostos aqui foram propostos
inicialmente pela comissão organizadora, mas **também serão aceitas
propostas para outros temas**.

As propostas para tutoriais devem conter as seguintes informações:

- Nome
- Email
- Universidade/Instituição/Empresa
- Título
- Destinado à: usuário/desenvolvedor/não se aplica
- Objetivo
- Nível (iniciante/intermediário/avançado)
- Pré-requisitos (se houver)
- Descrição

Estas informações devem ser preenchidas e encaminhadas através deste
[formulário](https://goo.gl/forms/H2KvxSvgNrsiFiZw1).

### Custeio

Até o momento o evento está sendo organizado de forma voluntária,
portanto não conta ainda com financiamento ou patrocinadores. Sendo
assim, por hora não existe garantia alguma de apoio financeiro aos
convidados e participantes do evento. Gentilmente, solicita-se que o
envio das propostas, portanto, não seja dependente de contrapartidas
financeiras por parte da organização do evento, ficando inicialmente, as
despesas de responsabilidade dos proponentes. Havendo êxito no
recebimento de qualquer auxílio, poderá haver ressarcimento parcial, ou
até total, das despesas dos convidados.
